server:
  addr: :8080
  base_url: http://localhost:8080

database:
  driver: postgres
  dsn: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable

kvstore:
  type: redis
  redis:
    addr: ${REDIS_HOST}:${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    db: ${REDIS_DB}

filestorage:
  type: local
  local:
    base_path: ./static/uploads

authentication:
  jwt:
    secret: ${JWT_SECRET}

telegram:
  token: ${TELEGRAM_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}

static:
  dir: ./static

schemas:
  schema: ./schemas/schema.v1.json
  pages: ./schemas/pages.v1.json
  layouts: ./schemas/layouts.v1.json
  blocks: ./schemas/blocks.v1.json
  modules: ./schemas/modules.v1.json
  shared: ./schemas/shared.v1.json